### ISSUE TITLE
Private QuickButtons throw an error when clicked on an inherited class.

### ISSUE THREAD

**Issue by hbraun87** [roboryantron/UnityEditorJunkie#9]
Ideally we can hide the button or throw a different error.

**Comment by roboryantron** [comment]
To clarify, protected buttons work, private buttons display in the inspector but error when clicked

**Comment by roboryantron** [comment]
Fixed in #10 hash d5394de

**Comment by roboryantron** [comment]
@hbraun87 clicking a private button in an inherited class will be still be invoked. I decided to follow the same pattern Unity does with with private fields in the inspector. 

Since private fields are still displayed and editable in the inspector when viewing an inheriting class, private buttons are also displayed and interactable
